# include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - signals_lint
  errors:
    unused_field: ignore
    deprecated_member_use: ignore
    unused_element_parameter: ignore
    prefer_final_fields: ignore

formatter:
  trailing_commas: preserve
