name: hospital
description: "A hospital simulation game"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  objectbox_generator: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  objectbox: ^4.1.0
  build_runner: ^2.4.15
  states_rebuilder: ^6.4.0
  uuid: ^4.5.1
  manager:
    path: ..//manager
  icons_plus: ^5.0.0 
  forui: ^0.9.1+1
  path_provider: ^2.1.5
  faker: ^2.2.0
flutter:
  uses-material-design: true
