name: hospital
description: "A hospital simulation game"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0
dependencies:
  states_rebuilder: ^6.4.0
  forui: 0.14.1
  flutter:
    sdk: flutter
  build_runner: ^2.4.15
  uuid: ^4.5.1
  icons_plus: ^5.0.0 
  path_provider: ^2.1.5
  faker: ^2.2.0
  signals: ^6.0.2
  hive_flutter: ^1.1.0
  package_info_plus: ^8.3.0
flutter:
  uses-material-design: true
