name: hospital
description: "A hospital simulation game"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.4.15
  uuid: ^4.5.1
  icons_plus: ^5.0.0
  path_provider: ^2.1.5
  faker: ^2.2.0
  signals_flutter: ^6.0.2
  hive_flutter: ^1.1.0
  package_info_plus: ^8.3.0
  hux: ^0.4.0
  navigation_builder: ^0.0.4
  forui: ^0.15.1
flutter:
  uses-material-design: true
