name: hospital
description: "A hospital simulation game"
publish_to: "none"
version: 0.1.0
environment:
  sdk: ^3.10.3
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  faker: ^2.2.0
  intl: ^0.20.2
flutter:
  uses-material-design: true
