name: hospital
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.23.0
  states_rebuilder: ^6.4.0
  uuid: ^4.5.1
  provider: ^6.1.2
  manager:
    path: ..//manager
  icons_plus: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  objectbox: ^4.0.3
  objectbox_generator: ^4.0.3
  objectbox_flutter_libs: ^4.0.3

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
